// editor/src/components/ConnectedLayout/DrawerComponent/index.tsx
import React, { ReactNode } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { Drawer } from 'antd';

import {
  COLLECTION_CATALOGUE,
  COLLECTION_SETTING,
  CONTACT_US,
} from '../../../utils/constants';

import CollectionCatalogue from './CollectionCatalogue';
import CollectionSetting from './CollectionSetting';
import ContactUs from './ContactUs';

import { RootState } from '../../../store';
import { DrawerState } from '../../../models';

const mapTypeToTitle: { [key: string]: string } = {
  [COLLECTION_CATALOGUE]: '文集目录',
  [COLLECTION_SETTING]: '文集设置',
  [CONTACT_US]: '联系我们',
};

const mapTypeToComponent: { [key: string]: ReactNode } = {
  [COLLECTION_CATALOGUE]: <CollectionCatalogue />,
  [COLLECTION_SETTING]: <CollectionSetting />,
  [CONTACT_US]: <ContactUs />,
};

function DrawerComponent() {
  const dispatch = useDispatch();
  const { drawerType, visible } = useSelector<RootState, DrawerState>(
    (state) => state.drawer,
  );

  const RenderComponent = mapTypeToComponent[drawerType];

  const handleClose = () => {
    dispatch({ type: 'drawer/setVisible', payload: false });
    dispatch({ type: 'drawer/setSelectedKeys', payload: [] });
  };

  return (
    <Drawer
      title={mapTypeToTitle[drawerType]}
      placement="left"
      width={300}
      visible={visible}
      onClose={handleClose}
      headerStyle={{
        background: '#F7F7FA',
      }}
      drawerStyle={{
        background: '#F7F7FA',
      }}
      zIndex={11}
      style={{ marginLeft: '80px' }}
    >
      {RenderComponent}
    </Drawer>
  );
}

export default DrawerComponent;

// packages/editor/src/components/drawer/Drawer.vue
<template>
  <a-drawer
    class="ml-20"
    placement="left"
    :zIndex="11"
    :width="300"
    :title="title"
    :visible="visible"
    @close="setVisible(false)"
  >
    <component :is="drawerType"></component>
  </a-drawer>
</template>

<script>
import { defineComponent } from 'vue-demi';
import { mapMutations, mapState } from 'vuex';

import CollectionCatalogue from './CollectionCatalogue.vue';
import CollectionSetting from './CollectionSetting.vue';
import ContactUs from './ContactUs.vue';

const mapTypeToTitle = {
  CollectionCatalogue: '文集目录',
  CollectionSetting: '文集设置',
  ContactUs: '联系我们',
};

export default defineComponent({
  name: 'Drawer',
  components: {
    CollectionCatalogue,
    CollectionSetting,
    ContactUs,
  },
  computed: {
    title() {
      return mapTypeToTitle[this.drawerType];
    },
    ...mapState('drawer', ['visible', 'drawerType']),
  },
  methods: {
    ...mapMutations('drawer', ['setVisible']),
  },
});
</script>

<style scoped></style>
